"""add lightweight persistent job and administration tables"""
from alembic import op
import sqlalchemy as sa
revision = '0002_lightweight_runtime'; down_revision = '0001_foundation'; branch_labels = None; depends_on = None
def upgrade():
    op.create_table('jobs', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('job_type', sa.String(80), nullable=False), sa.Column('status', sa.String(20), nullable=False), sa.Column('payload', sa.Text(), nullable=False), sa.Column('progress', sa.Integer(), nullable=False), sa.Column('total', sa.Integer(), nullable=False), sa.Column('processed', sa.Integer(), nullable=False), sa.Column('attempts', sa.Integer(), nullable=False), sa.Column('max_attempts', sa.Integer(), nullable=False), sa.Column('error', sa.Text()), sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')), sa.Column('started_at', sa.DateTime()), sa.Column('completed_at', sa.DateTime()), sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')))
    op.create_index('ix_jobs_status', 'jobs', ['status']); op.create_index('ix_jobs_type', 'jobs', ['job_type'])
    op.create_table('instruction_profiles', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(160), nullable=False, unique=True), sa.Column('niche', sa.String(160), nullable=False), sa.Column('language', sa.String(40), nullable=False), sa.Column('tone', sa.String(80), nullable=False), sa.Column('offer', sa.Text(), nullable=False), sa.Column('services', sa.Text(), nullable=False), sa.Column('cta', sa.Text(), nullable=False), sa.Column('rules', sa.Text(), nullable=False), sa.Column('do_not_say', sa.Text(), nullable=False), sa.Column('personalization_rules', sa.Text(), nullable=False), sa.Column('additional_instructions', sa.Text(), nullable=False), sa.Column('active', sa.Boolean(), nullable=False), sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')))
    op.create_table('voice_agent_configs', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(160), nullable=False), sa.Column('base_url', sa.Text(), nullable=False), sa.Column('health_path', sa.String(200), nullable=False), sa.Column('call_path', sa.String(200), nullable=False), sa.Column('enabled', sa.Boolean(), nullable=False))
def downgrade():
    op.drop_table('voice_agent_configs'); op.drop_table('instruction_profiles'); op.drop_index('ix_jobs_type'); op.drop_index('ix_jobs_status'); op.drop_table('jobs')
