"""core lead, audit, message, service profile and integration records"""
from alembic import op
import sqlalchemy as sa
revision='0003_core_leads'; down_revision='0002_lightweight_runtime'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('leads',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('business_id',sa.Integer(),sa.ForeignKey('businesses.id'),nullable=False,unique=True),sa.Column('lifecycle',sa.String(30),nullable=False),sa.Column('score',sa.Integer(),nullable=False),sa.Column('grade',sa.String(20),nullable=False),sa.Column('score_reasons',sa.Text(),nullable=False));op.create_index('ix_leads_business_id','leads',['business_id']);op.create_index('ix_leads_lifecycle','leads',['lifecycle']);op.create_index('ix_leads_score','leads',['score'])
    op.create_table('website_audits',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('business_id',sa.Integer(),sa.ForeignKey('businesses.id'),nullable=False,unique=True),sa.Column('status',sa.String(40),nullable=False),sa.Column('evidence',sa.Text(),nullable=False),sa.Column('audited_at',sa.DateTime(),server_default=sa.text('CURRENT_TIMESTAMP')));op.create_index('ix_website_audits_business_id','website_audits',['business_id'])
    op.create_table('service_profiles',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_name',sa.String(200),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('services',sa.Text(),nullable=False),sa.Column('target_niches',sa.Text(),nullable=False),sa.Column('target_locations',sa.Text(),nullable=False),sa.Column('offer',sa.Text(),nullable=False),sa.Column('portfolio_url',sa.Text(),nullable=False),sa.Column('contact_information',sa.Text(),nullable=False),sa.Column('cta',sa.Text(),nullable=False),sa.Column('preferred_tone',sa.String(80),nullable=False),sa.Column('additional_instructions',sa.Text(),nullable=False))
    op.create_table('messages',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('lead_id',sa.Integer(),sa.ForeignKey('leads.id'),nullable=False),sa.Column('instruction_profile_id',sa.Integer(),sa.ForeignKey('instruction_profiles.id')),sa.Column('channel',sa.String(30),nullable=False),sa.Column('recipient',sa.String(320),nullable=False),sa.Column('subject',sa.String(300),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.text('CURRENT_TIMESTAMP')));op.create_index('ix_messages_lead_id','messages',['lead_id']);op.create_index('ix_messages_status','messages',['status'])
    op.create_table('integrations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('provider',sa.String(80),unique=True,nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('last_error',sa.Text(),nullable=False),sa.Column('last_test_at',sa.DateTime()))
def downgrade():
    op.drop_table('integrations');op.drop_index('ix_messages_status');op.drop_index('ix_messages_lead_id');op.drop_table('messages');op.drop_table('service_profiles');op.drop_index('ix_website_audits_business_id');op.drop_table('website_audits');op.drop_index('ix_leads_score');op.drop_index('ix_leads_lifecycle');op.drop_index('ix_leads_business_id');op.drop_table('leads')
